services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mcm-user
      POSTGRES_PASSWORD: mcm-password
      POSTGRES_DB: mcm-donaciones
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025

